export const AUTH_START = 'AUTH_START'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const GET_EMPLOYEES_START = 'GET_EMPLOYEES_START'
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS'
export const GET_EMPLOYEES_FAILURE = 'GET_EMPLOYEES_FAILURE'
export const FILTER_EMPLOYEES = "FILTER_EMPLOYEES";


export const    CLEAR_ERRORS = 'CLEAR_ERRORS';


export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';
export const ADD_ID = "ADD_ID"

export const REMOVE_EMPLOYEE = "REMOVE_EMPLOYEE"
export const REMOVE_EMPLOYEE_FAILURE = "REMOVE_EMPLOYEE_FAILURE"

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE"
export const SET_EMPLOYEE = "SET_EMPLOYEE"